### ISSUE TITLE
HRESULT: 0xC0048021

### ISSUE THREAD

**Issue by henrick-tissink** [fpvmorais/EzApi2016#2]
Hi, I'm getting HRESULT: 0xC0048021 exception when I try to create an EzScript component. I'm using SQLServer 2016. Do you perhaps have any tips for me on how to get this working?

**Comment by fpvmorais** [comment]
Hi Henrick,

According to this [Integration Services Error and Message Reference | Microsoft Docs](https://docs.microsoft.com/en-us/sql/integration-services/integration-services-error-and-message-reference)  0xC0048021	-1073446879	DTS_E_ERRORCOMPONENT

Can be DLL version issues. Can you send me a minimal example where the issue occurs?

Thank's

**Comment by fpvmorais** [comment]
I've think I know what was the cause. I've commited a new version to Beta branch. Can you please test to see if it solves your issue?

Thank you.

**Comment by henrick-tissink** [comment]
Hi, I solved the issue my side on Friday - it needed a reference to the Microsoft.SqlServer.TxScript.dll (version 11.0.0.0) I think I was using version 13.0.0.0.  

Just checked your last commit into the beta - that fixed it! Thanks a bunch man :) this is a great repo!

**Comment by fpvmorais** [comment]
In the code it was forcing version 11. I've taken that part out and now you can use the one installed in your machine.

Glad to help.
