### ISSUE TITLE
Unable to execute package from web application

### ISSUE THREAD

**Issue by VAlagar** [fpvmorais/EzApi2016#5]
I am trying to create a web api which will internally use the ezapi to execute packages. When i execute the package via my webapi, the visual studio seems to crash and the eventviewer has logged this issue

Faulting application name: devenv.exe, version: 15.8.28010.2048, time stamp: 0x5bce1e2b
Faulting module name: ntdll.dll, version: 10.0.17134.471, time stamp: 0xfe852bc4
Exception code: 0xc0000374
Fault offset: 0x000d8499
Faulting process ID: 0x99c
Faulting application start time: 0x01d4ba647850d482
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 40fc16a1-26a3-4ede-8917-9fd221a45c02
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fpvmorais** [comment]
Can you send me please a small sample that I can test to see if I can help you?

Thanks

**Comment by VAlagar** [comment]
Thank you so much for getting back, I managed to resolve it by setting some policy changes for the SSIS to be able to run under my windows account and as the IIS users was not able to run the SSIS and it was crashing for that reason.

I am delighted to say that the EzAPI is working great !! & works well with the web API as well!!
